# Generated by Django 4.0.1 on 2024-01-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_categorymodel_productmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='category',
        ),
    ]
